### ISSUE TITLE
GoError

### ISSUE THREAD

**Issue by fbagjug** [SuperPykkon/GoMinewrap#2]
Getting this error when trying to run "go run mcs.go"

> mcs.go:5:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /root/work/src/context (from $GOPATH)

**Comment by SuperPykkon** [comment]
Hey there, sorry for the late response.
Can you tell me what GoLang version you're running? Please make sure it's go1.8

**Comment by fbagjug** [comment]
Ok so i checked my version and it says 1.6.2 linux so im gonna try to update it

**Comment by fbagjug** [comment]
Im not sure if im running the correct command "apt-get install golang"

**Comment by SuperPykkon** [comment]
I recommend downloading the latest version from the golang website here: https://golang.org/dl/ and manually installing it. Here are the instructions: https://golang.org/doc/install#install 

All the commands to execute are given there. Let me know if you have any trouble while or after installing it :).

**Comment by fbagjug** [comment]
I tried the manual download and it doesnt seem to work. I will keep trying

**Comment by SuperPykkon** [comment]
Can you tell me what doesn't seem to work? Like the errors you're getting?
Or is it that the go command isn't working? But the installation went fine? If so, you'll have to make sure  to export the path with `export PATH=$PATH:/usr/local/go/bin` also, to be on the safer side, it's best if you paste that export command on the very bottom of the ~/.bashrc file.

Simply `nano ~/.bashrc`, scroll to the bottom and paste `export PATH=$PATH:/usr/local/go/bin`. Restart the terminal and see if it works.

**Comment by SuperPykkon** [comment]
Hello there, any news on how the installation went?

**Comment by humaidq** [comment]
Bug has been fixed. :smiley: Should now work with Go 1.6

**Comment by fbagjug** [comment]
Go is fucked up for me.

**Comment by SuperPykkon** [comment]
Ok. If you did update GoLang, why don't you just use the GoMinewrap pre-compiled executables? Download here: https://github.com/SuperPykkon/GoMinewrap/releases/tag/0.3.1

**Comment by fbagjug** [comment]
The thing about updating GoLang is that it doesnt update. I follow the install instructions and none of it works. I will continue to try but idk

**Comment by SuperPykkon** [comment]
If you can tell me the error you got while trying to update GoLang, I'd be glad to help you fix it :P
